### ISSUE TITLE
Some GTK apps don't work with the theme - Tried other themes and they worked

### ISSUE THREAD

**Issue by 404oops** [EliverLara/Kripton#14]
![image](https://user-images.githubusercontent.com/51266541/130850858-a2dd5513-6a60-428d-865d-426b56d52d43.png)
As you can see, i have two GTK apps opened, and they don't respond to the current theme, which is Kripton for gnome 40
Any way to fix this? I thought that my dark mode switcer was buggy but it wasn't

**Comment by falidea** [comment]
I have the same Problem
![pic1](https://user-images.githubusercontent.com/73386942/132820821-0ece4ec6-03c2-4d09-8fac-4b5ba5f670c8.png)

**Comment by EliverLara** [comment]
I think it is caused by using gtk4 in those apps, I'll try to add support to gtk4 ASAP
