### ISSUE TITLE
change xfwm4 color

### ISSUE THREAD

**Issue by skydie22** [EliverLara/Kripton#15]
hello , how to change xfwm4 theme color ?

**Comment by EliverLara** [comment]
HI, you must do the following:

1.  Update the `.svg` files inside `xfwm4/assets`.
2. Run the `render_assets.fish` file inside `xfwm4/`

**Comment by skydie22** [comment]
> HI, you must do the following:
> 
> 1. Update the `.svg` files inside `xfwm4/assets`.
> 2. Run the `render_assets.fish` file inside `xfwm4/`

thanks for you reply but can i run .fish whereas I use bash ? 
pliss make the bash script 
thankyou very much
