### ISSUE TITLE
Nautilus on Gnome

### ISSUE THREAD

**Issue by sigmamale1980** [EliverLara/Kripton#24]
Invisible max,min and close buttons on Nautilus Gnome. I tried linking gtk-4.0 to ~/.config/gtk-4.0, didn't work. everything else on gnome 43 is ok except for nautilus file manager.

**Comment by paulo-roger** [comment]
For me the buttons show, but they are not changed by the theme. It is not as bad but still annoying. I think this might be something on nautilus side?

**Comment by EliverLara** [comment]
Hi, I'm sorry for the very late response, if you're still experiencing this issue with this or other themes using [this script](https://github.com/odziom91/libadwaita-theme-changer) should fix that issue
