### ISSUE TITLE
Gnome Nautilus Window Controls

### ISSUE THREAD

**Issue by paulo-roger** [EliverLara/Kripton#25]
Hola, por alguna razon no estan cambiando los controlos de la window en nautilus.

sabes como podriamos mejorar eso?

**Comment by EliverLara** [comment]
Hola, una disculpa por la respuesta tan tardia, supongo que estas usando las versiones mas recientes de gnome, lo mas recomendable es usar [este script](https://github.com/odziom91/libadwaita-theme-changer) ya que con ese script se copian todos los assets requeridos.

**Comment by paulo-roger** [comment]
Gracias!
