### ISSUE TITLE
Check marks & Radio buttons are not Visible and are Not Centered

### ISSUE THREAD

**Issue by ZN0N15** [EliverLara/Kripton#26]
Check marks seem to be completely invisible. I thought it was a gnome issue at first but I tried other environments like xfce and even using lxappearance to apply the theme but the check marks in checkboxes are just not visible.

![screenshot2023-08-15-12:54:25](https://github.com/EliverLara/Kripton/assets/57549197/382f35e8-054d-4379-959b-927f71edef0b)

Edit:
I've just found that the issue is the assets are completely broken for checkbox and radio button. I've installed the theme via the AUR which seems to be the cause. After cloning the repo manually the assets seem to be fine and just pasted it to the themes folder.

However, theres a completely different issue. Some Checkbox and Radio buttons are completely off-centered and they're clipping to the right it seems.

![screenshot2023-08-15-14:15:13](https://github.com/EliverLara/Kripton/assets/57549197/8559631b-b5d3-49c8-9c59-7abf32754d01)
![screenshot2023-08-15-14:14:53](https://github.com/EliverLara/Kripton/assets/57549197/5c80937c-bd63-437e-a469-9b646db1fba9)
![screenshot2023-08-15-14:14:37](https://github.com/EliverLara/Kripton/assets/57549197/394bbe60-4e73-4232-8132-3fea04a52430)
![screenshot2023-08-15-14:14:25](https://github.com/EliverLara/Kripton/assets/57549197/76dafc54-3868-428e-a59c-e1852c19b4da)

**Comment by EliverLara** [comment]
That was fixed with d01f21dd94a034ff90e3e7007b483cd9df2674ca a long time ago
