### ISSUE TITLE
minimize, maximize and close buttons are not visible for gtk-4.0 version on gnome apps

### ISSUE THREAD

**Issue by mhkdepauw** [EliverLara/Kripton#27]
example:
![image](https://github.com/EliverLara/Kripton/assets/87832202/7f163a91-0333-4c4d-a558-d47825b29504)

**Comment by EliverLara** [comment]
Hi, I'm sorry for the very late response but in case you still need it it's easily fixable by using [this script](https://github.com/odziom91/libadwaita-theme-changer)

**Comment by mhkdepauw** [comment]
That actually did the opposite and removed the theme from some of my applications it was previously working on (except for the buttons).

**Comment by mhkdepauw** [comment]
I managed to fix that and am still struggling to get some applications to the buttons but it's better than before.
