### ISSUE TITLE
Custom accents colour

### ISSUE THREAD

**Issue by akemrir** [EliverLara/Kripton#5]
For starters I need to say: Very nice and dark coloured theme. I love it.

Could you help with getting custom accent colour?
I have following script to update to my custom colour.

```
rg F6BB77 -l | xargs -I col sed -i 's/9bbfbf/F6BB77/gi' col
rg BDD2A6 -l | xargs -I col sed -i 's/BDD2A6/F6BB77/gi' col

cd ~/.themes/Kripton/gtk-2.0
bash render-assets.sh
fish links.fish
```

But it seems some controls are not changed.
Am I missing something?

**Comment by akemrir** [comment]
![pic-selected-200910-1003-21](https://user-images.githubusercontent.com/240986/92698742-0b8c5900-f34d-11ea-88f8-c5ddb7f721a6.png)

This is intentional?

**Comment by EliverLara** [comment]
Hi, in addition to what you have done in your script you must do the following:

- Replace the `selected_bg_color` variable in the `Kripton/gtk2.0/gtkrc` file.
- Change the `$selected_bg_color` variable in the` _colors.scss` file (under Kripton/gtk-3.0/),
- Recompile the `gtk.scss` file to generate the corresponding `css`
- Reload the theme

 **Note**
 To recompile  `gtk.scss` just type in your terminal (you must have [sass](http://sass-lang.com/install) installed ): 
`sass gtk.scss gtk.css`

**Comment by akemrir** [comment]
![pic-selected-200911-1012-05](https://user-images.githubusercontent.com/240986/92890495-74d89e80-f417-11ea-8f72-28c8f6d20358.png)

Thanks for help. Almost done :)
Now this checkboxlike element and I will have finished script.

**Comment by akemrir** [comment]
What about gtk3 assets?
Do I need to move them when running python scripts in src?

**Comment by akemrir** [comment]
Ok, I run them but I am getting error about verb.
I have versions of apps:
- inkscape 1.0
- python 3.8.5

**Comment by akemrir** [comment]
I ve tried to modify python scripts, but I failed at it. They hang when recompiling assets.
On which apps versions you are running them?

**Comment by akemrir** [comment]
Ok, found it. This script is using old shell syntax which is not compatible with newer versions of inkscape.

**Comment by akemrir** [comment]
Ok, I've managed out how to do it properly. I am closing this ticket.
